#!/usr/bin/env bash

set -o errexit                                                                  
set -o pipefail                                                                 
set -o nounset                                                                  
__src_cli_call="${BASH_SOURCE[0]}"                                              
__src_location="$(cd "$(dirname "${__src_cli_call}")" && pwd )"                 
__src_absolute="${__src_location}/$(basename "${__src_cli_call}")"              
__src_name="$(basename "${__src_absolute}")"                                    
__src_home="$(cd "$(dirname "${__src_location}")" && pwd)"                      
__src_sessionid=$(echo ${USER}-$(hostname)-${$} | md5sum | awk '{print $1}')

function is-yum-installed () {
    if yum -q list installed "${1}" >/dev/null 2>&1; then
        true
    else
        false
    fi
}

function verify-libxml () {
    local err=0
    local yum_libxml=("libxml2-devel" "libxslt-devel" "python-devel")
    local msg=""
    while [[ ${yum_libxml#} > 0 ]]
    do
        msg="Installed"
        package=${yum_libxml[0]}
        if ! is-yum-installed ${package};then
            err=1
            msg="Missing"
        fi
        echo "${package} ${msg}"

        #shift off first array element
        yum_libxml=(${yum_libxml[@]:1})
    done
    if [[ $err == 1 ]];then
        echo "Install missing packages before proceeding with current install."
        exit 1
    fi
}

verify-libxml
