#!/usr/bin/env bash

set -o errexit                                                                  
set -o pipefail                                                                 
set -o nounset                                                                  
__src_cli_call="${BASH_SOURCE[0]}"                                              
__src_location="$(cd "$(dirname "${__src_cli_call}")" && pwd )"                 
__src_absolute="${__src_location}/$(basename "${__src_cli_call}")"              
__src_name="$(basename "${__src_absolute}")"                                    
__src_home="$(cd "$(dirname "${__src_location}")" && pwd)"                      
__src_sessionid=$(echo ${USER}-$(hostname)-${$} | md5sum | awk '{print $1}')

function is-yum-installed () {
    if yum list installed "$@" >/dev/null 2>&1; then
        true
    else
        false
    fi
}


function virtual-wrapper () {
    local cmd="${1}"
    local __bin="${__src_home}/bin"
    local __lbin="${__src_home}/local/bin"
    local __cmd_file="${__lbin}/${cmd}"
    echo "set +o nounset" >> "${__cmd_file}"
    printf "source \"%s\"\n" "${__src_home}/opt/python3.3/bin/activate" >> "${__cmd_file}"
    echo "set -o nounset" >> "${__cmd_file}"
    printf "%s \"\$@\"\n" "${cmd}" >> "${__cmd_file}"

    chmod +x "${__cmd_file}"
}

virtual-wrapper "$@"
